tool/script/*: implement usage and `--help` options, improve error handling

diff --git a/tool/script/wrrarms-w3m b/tool/script/wrrarms-w3m
--- a/tool/script/wrrarms-w3m
+++ b/tool/script/wrrarms-w3m
@@ -1,5 +1,31 @@
-#!/bin/sh -e
-# purpose: generate a plain text preview of a WRR file via `w3m`
+#!/usr/bin/env bash
+set -e
+
+usage() {
+    cat << EOF
+usage: $0 [--help] WRR_FILE
+
+Generate a plain text preview of a WRR file containing an HTML document using \`w3m\`.
+
+# Options:
+
+  --help                print this message and exit
+
+# Example:
+
+  $0 path/to/wrr/file/containing/html.wrr
+EOF
+}
+
+while (($# > 0)); do
+    case "$1" in
+    --help) usage; exit 0 ;;
+    *) break ;;
+    esac
+    shift
+done
+
+(($# > 0)) || { echo "error: need a WRR_FILE"; echo; usage; exit 1; } >&2
 
 wrrarms get -l \
         -e "net_url|add_prefix '# url: '" \
diff --git a/tool/script/wrrarms-xdg-open b/tool/script/wrrarms-xdg-open
--- a/tool/script/wrrarms-xdg-open
+++ b/tool/script/wrrarms-xdg-open
@@ -1,5 +1,32 @@
-#!/bin/sh -e
-# purpose: open `response.body` of the given WRR file with `xdg-open`
-# this works for Debian's `xdg-open`, which waits for the child process to finish, will probably fail otherwise
+#!/usr/bin/env bash
+set -e
 
-exec wrrarms run -- xdg-open "$1"
+usage() {
+    cat << EOF
+usage: $0 [--help] WRR_FILE
+
+Open \`response.body\` of the given WRR file with \`xdg-open\`.
+
+This script only works for Debian's \`xdg-open\`, which waits for the child process to finish.
+
+# Options:
+
+  --help                print this message and exit
+
+# Example:
+
+  $0 path/to/wrr/file.wrr
+EOF
+}
+
+while (($# > 0)); do
+    case "$1" in
+    --help) usage; exit 0 ;;
+    *) break ;;
+    esac
+    shift
+done
+
+(($# > 0)) || { echo "error: need a WRR_FILE"; echo; usage; exit 1; } >&2
+
+exec wrrarms run -- xdg-open "$@"
diff --git a/tool/script/wrrarms-xdg-open-mimi b/tool/script/wrrarms-xdg-open-mimi
--- a/tool/script/wrrarms-xdg-open-mimi
+++ b/tool/script/wrrarms-xdg-open-mimi
@@ -1,4 +1,32 @@
-#!/bin/sh -e
-# like `wrrarms-xdg-open`, but for `mimi`'s `xdg-open`
+#!/usr/bin/env bash
+set -e
+
+usage() {
+    cat << EOF
+usage: $0 [--help] WRR_FILE
+
+Open \`response.body\` of the given WRR file using Mimi's \`xdg-open\`.
+
+This will also work for other similar \`xdg-open\` scripts that do not wait for their child process to finish unless you specify \`--wait\`.
+
+# Options:
+
+  --help                print this message and exit
+
+# Example:
+
+  $0 path/to/wrr/file.wrr
+EOF
+}
+
+while (($# > 0)); do
+    case "$1" in
+    --help) usage; exit 0 ;;
+    *) break ;;
+    esac
+    shift
+done
+
+(($# > 0)) || { echo "error: need a WRR_FILE"; echo; usage; exit 1; } >&2
 
 exec wrrarms run -- xdg-open --wait "$1"
